export const MoviesActionTypes = {
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  SET_IS_LOADING_SEARCH: 'SET_IS_LOADING_SEARCH',
  SET_SEARCH_ERROR: 'SET_SEARCH_ERROR',
  SET_SEARCH_OPTIONS: 'SET_SEARCH_OPTIONS',
  SET_MOVIES_LIST: 'SET_MOVIES_LIST',
  SET_MOVIES_PAGE: 'SET_MOVIES_PAGE'
};
